/** Turn a Dataset into INSERT statements for supabase/seed.sql. */
import type { Dataset } from "../src/lib/domain/types";

type Row = Record<string, unknown>;

function lit(v: unknown): string {
  if (v === null || v === undefined) return "null";
  if (typeof v === "number") return Number.isFinite(v) ? String(v) : "null";
  if (typeof v === "boolean") return v ? "true" : "false";
  if (typeof v === "object") return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
  return `'${String(v).replace(/'/g, "''")}'`;
}

function snake(k: string): string {
  return k.replace(/[A-Z]/g, (c) => `_${c.toLowerCase()}`);
}

function insert(table: string, rows: Row[], columns: string[]): string {
  if (!rows.length) return `-- ${table}: no rows\n`;
  const cols = columns.map(snake).join(", ");
  const chunks: string[] = [];
  for (let i = 0; i < rows.length; i += 200) {
    const values = rows
      .slice(i, i + 200)
      .map((r) => `  (${columns.map((c) => lit(r[c])).join(", ")})`)
      .join(",\n");
    chunks.push(`insert into ${table} (${cols}) values\n${values}\non conflict do nothing;\n`);
  }
  return chunks.join("\n");
}

export function datasetToSql(ds: Dataset): string {
  const parts = [
    "-- Generated by scripts/build-seed.ts. Do not edit by hand; run `npm run seed:build`.",
    "-- Loads NSE Spring 26 (Division 2 + Swiss) into an empty database.",
    "",
    insert("seasons", ds.seasons as unknown as Row[], ["id", "slug", "name", "shortName", "isCurrent", "isFinished"]),
    insert("teams", ds.teams as unknown as Row[], ["id", "slug", "name", "shortName", "nseSlug", "ourKey"]),
    insert("team_seasons", ds.teamSeasons as unknown as Row[], ["seasonId", "teamId", "tier", "nseTournamentSlug"]),
    insert("nights", ds.nights as unknown as Row[], ["id", "seasonId", "tier", "stage", "week", "label", "date", "venue"]),
    insert("series", ds.series as unknown as Row[], [
      "id", "seasonId", "tier", "nseMatchId", "stage", "nightId", "round", "playoffRound",
      "homeTeamId", "awayTeamId", "homeScore", "awayScore", "bestOf", "isForfeit", "playedAt",
    ]),
    insert("external_night_results", ds.externalResults as unknown as Row[], ["nightId", "teamId", "points", "status"]),
    insert("external_standings", ds.externalStandings as unknown as Row[], [
      "seasonId", "tier", "teamId", "position", "total", "playoffNote",
    ]),
    insert("players", ds.players as unknown as Row[], ["id", "slug", "nickname", "nseProfileUrl", "platformIds"]),
    insert("roster_entries", ds.roster as unknown as Row[], ["teamId", "seasonId", "playerId", "role"]),
  ];
  return parts.join("\n") + "\n";
}
